baseURL = 'https://licht1stein.github.io'
languageCode = 'en-us'
title = 'Keep Thinking'
timeZone = 'Europe/Lisbon'

[Params.social.share]
  facebook = true
  linkedin = true
  twitter = true
  whatsapp = false
  email = true
