baseURL = 'https://keepthinking.blog/'
languageCode = 'en-us'
languageName = "English"
hasCJKLanguage = false
title = 'Keep Thinking'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/dillonzq/LoveIt"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false  is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true

[params]
    title = "Keep Thinking"
    description = "A blog about critical thinking during the war in Ukraine and modern times in general"
    defaultTheme = "auto"
    images = ["/logo.png"]

[params.social]
    RSS = true

[params.home.profile]
    enable = true
    subtitle = ""
    typeit = false
    social = true
    align = "left"

[params.header]
    desktopMode = "normal"
    mobileMode = "auto"

[params.header.title]
    name = "Keep Thinking"
    typeit = true

[params.footer]
    enable = true
    hugo = false
    license = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>"

[params.list]
    rss = 10

[params.page]
rssFullText = true

[params.page.share]
    enable = false
    Twitter = true
    Facebook = true
    Telegram = true
    Weibo = false
    Reddit = true
    Line = false
    HackerNews = false
    Whatsapp = true

[params.page.comment]
    enable = false
[params.page.comment.telegram]
    enable = false
    siteID = "JtLmc_ju"
    limit = 5
    height = ""
    color = ""
    colorful = true
    dislikes = false
    outlined = false